/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2015-04-08 14:00:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Ajax和Json</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction getArray() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar xmlHttp=new XMLHttpRequest();\r\n");
      out.write("\t\t\txmlHttp.open(\"get\", \"jsonServlet\", true);\r\n");
      out.write("\t\t\txmlHttp.send();\r\n");
      out.write("\t\t\txmlHttp.onreadystatechange= function(){\r\n");
      out.write("\t\t\t\tif(xmlHttp.readyState==4&&xmlHttp.status==200){\r\n");
      out.write("\t\t\t\t\talert(xmlHttp.responseText);\r\n");
      out.write("\t\t\t\t\t//转化Object类型 \r\n");
      out.write("\t\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\t*1.var json = (new Function('return '+param +';'))();\r\n");
      out.write("\t\t\t\t\t*2.eval('var json = '+param);\r\n");
      out.write("\t\t\t\t\t*/\r\n");
      out.write("\t\t\t\t\tvar dataObj=eval('(' + xmlHttp.responseText + ')');\r\n");
      out.write("\t\t\t\t\tvar tableObj=document.getElementById(\"tab\");\r\n");
      out.write("\t\t\t\t\tvar row; //行\r\n");
      out.write("\t\t\t\t\tvar col1; //第一列\r\n");
      out.write("\t\t\t\t\tvar col2; //第二列\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<dataObj.students.length;i++){\r\n");
      out.write("\t\t\t\t\t\tvar student=dataObj.students[i];\r\n");
      out.write("\t\t\t\t\t\trow=tableObj.insertRow(); //将新行添加到表的最后\r\n");
      out.write("\t\t\t\t\t\tcol1=row.insertCell();//第一列\r\n");
      out.write("\t\t\t\t\t\tcol2=row.insertCell();//第二列\r\n");
      out.write("\t\t\t\t\t\tcol1.innerHTML=student.name;\r\n");
      out.write("\t\t\t\t\t\tcol2.innerHTML=student.age;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"button\" value=\"ajax获取值\" onclick=\"getArray()\"><br><br>\r\n");
      out.write("\t\t\t<table id=\"tab\" border=\"1\" align=\"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>姓名</th>\r\n");
      out.write("\t\t\t\t\t<th>年龄</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
